language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run test-ci
  - npm run lint
after_script:
  - yarn add codecov
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - node_modules/.bin/codecov
